platform :ios, '10.0'
use_frameworks!

def shared_pods
    pod 'AccuTerra-Mapbox-iOS-SDK', :podspec => 'https://accuterra-builds.s3.amazonaws.com/map-sdk/ios/5.7.0.5/AccuTerra-Mapbox-iOS-SDK.podspec'
    pod 'AccuTerraSDK', :path => 'AccuTerraSDK.podspec'
end

target 'Controlling-The-Map' do
    shared_pods
end
