source 'https://github.com/CocoaPods/Specs.git'
source 'https://rp3uxdp6aso42eq3l4pzqriztcn4e3qxeyxzxnbx7xrjgqgjmpaq:rp3uxdp6aso42eq3l4pzqriztcn4e3qxeyxzxnbx7xrjgqgjmpaq@neotreks.visualstudio.com/Cocoapods/_git/Specs/'
platform :ios, '10.0'
use_frameworks!

def shared_pods
  pod 'AccuTerraSDK', :path => 'AccuTerraSDK.podspec'
end

target 'AccuterraSampleApp' do
    shared_pods
end
